### ISSUE TITLE
ProxyRequest expects source to be Optional[List[str]] but on quepid add new case, a string "*" is sent

### ISSUE THREAD

**Issue by leobeal** [amboss-mededu/quepid-es-proxy#3]
That will cause the following error on the "add new case" modal.
 
<img width="1337" alt="Screenshot 2021-01-06 at 10 26 07" src="https://user-images.githubusercontent.com/12049134/103752156-a0584800-5009-11eb-9ac1-b310c937ad7e.png">

**Comment by smirnoffs** [comment]
Thanks!
