### ISSUE TITLE
Update public docker image

### ISSUE THREAD

**Issue by vincetrumental** [amboss-mededu/quepid-es-proxy#8]
Hi, 
Would it be possible to update the public Docker Image (https://quay.io/amboss-mededu/quepid_es_proxy ) ?
This image does not currently include the latest developments (Basic Auth on elasticsearch). 
This could also fix some (or more?) [vulnerabilities reported](https://quay.io/repository/amboss-mededu/quepid_es_proxy/manifest/sha256:e9c32a35a7cbf159345d0bc1bc494b68e6a772ab94911cd162ab31a760672e18?tab=vulnerabilities) .
Thanks !

**Comment by smirnoffs** [comment]
@vincetrumental I'll have to remove the image from `quay.io`, it's not free for OSS anymore.

**Comment by smirnoffs** [comment]
@vincetrumental Thanks for reporting vulnerabilities. I have updated dependencies and now everything looks good again.
